
name: Backup Mastodon Account
on:
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Backup Mastodon Account
        uses: potatoqualitee/fossilize@v1
        id: backup
        with:
          server: fulda.social
        env:
          ACCESS_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
